blueprint:
  name: Presence-activated light controller with preset memory
  description: A template for an area-of-influence of a single presence sensor. Remembers and restores the last light status upon return.
  domain: automation
  input:

    presence_sensor:
      name: "Presence sensor"
      description: "It's presence will manage the lights turning on and off. Can be shared between any automation or set of lights."
      selector:
        entity:
          filter:
            device_class: occupancy

    presence_timeout:
      name: "Presence timeout"
      description: "Delay turning the lights off to prevent unnecessary light flipping. This delay is additive to any presence timeouts/delays configured at the presence sensor level."
      default: 0
      selector:
        duration:

    daylight_independent:
      name: "Turn the lights on during the day"
      description: "By default the automation lights up lights only after daylight is gone. Toggle this on for areas with no access to daylight, eg. bathrooms, cellars."
      default: false
      selector:
        boolean:

    lights_on:
      name: "Lights to be turned on"
      description: "Will be always turned on upon entering the area(s) or being present in the area when the daylight ends."
      selector:
        target:
          entity:
            domain: light

    lights_off:
      name: "Lights to be turned off"
      description: "Will be always turned off upon leaving the area(s)"
      selector:
        target:
          entity:
            domain: light

    lights_off_exclude:
      name: "...excluding these lights"
      description: "Optional, excludes selected lights from the above set."
      default: []
      selector:
        target:
          entity:
            domain: light

    lights_restore:
      name: "Lights to be tracked and restored"
      description: "Will be turned on upon entering the area(s) if they were turned on when leaving last time."
      selector:
        target:
          entity:
            domain: light

    lights_restore_exclude:
      name: "...excluding these lights"
      description: "Optional, excludes selected lights from the above set."
      default: []
      selector:
        target:
          entity:
            domain: light

    restore_scene_ttl:
      name: "Restore state expiration"
      description: "Optional, prevents lights being restored after the defined period of inactivity has passed. Useful when you like to revert lights to a certain default state."
      default: 0
      selector:
        duration:

alias: "{area}: Turn lights on/off based on a presence sensor"
description: ""

triggers:

  # Trigger when presence begins, no delay

  - trigger: state
    alias: Entering the area
    entity_id: !input presence_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: presence_on
    from: "off"
    to: "on"

  # Trigger when presence ends, with a configured delay

  - trigger: state
    alias: Leaving the area (delayed)
    entity_id: !input presence_sensor
    from: "on"
    to: "off"
    for: !input presence_timeout
    id: presence_off

  # Trigger when presence ends, with a configured delay

  - trigger: state
    entity_id:
      - binary_sensor.daylight
    from: "on"
    id: daylight_off

conditions: []

actions:


  - alias: "Prepare automation"
    sequence:

    # Expand target selectors into entities.

      - action: script.expand_entities
        response_variable: lights_off
        data:
          target: !input lights_off
          domain: light

      - action: script.expand_entities
        response_variable: lights_off_exclude
        data:
          target: !input lights_off_exclude
          domain: light

      - action: script.expand_entities
        response_variable: lights_restore
        data:
          target: !input lights_restore
          domain: light

      - action: script.expand_entities
        response_variable: lights_restore_exclude
        data:
          target: !input lights_restore_exclude
          domain: light

      - variables:

          # Pull some template inputs into variables.

          daylight_independent: !input daylight_independent
          restore_scene_ttl: !input restore_scene_ttl

          # Generate a name for the temporary light recovery scene

          scene_name: "{{ 'tmp_restorable_lights_for_' + this.entity_id | slugify() }}"

          # Generate the list of lights to be turned off when no presence.

          lights_off_entities: |
            {{ lights_off.entities | difference(lights_off_exclude.entities) | select('is_state', 'on') | list }}

          # Generate the list of lights to be saved when turning off and restored when presence is back.

          lights_restore_entities: |
            {{ lights_restore.entities | difference(lights_restore_exclude.entities) | select('is_state', 'on') | list }}

          # Check if any lights are on

          any_lights_on: >
            {{ lights_restore_entities | count > 0 }}

  - choose:

      # Conditions for lights ON

      - alias: "Lights ON"
        conditions:

          - condition: or
            conditions:

              # Lights on when entering the area(s)

              - condition: and
                alias: "Triggered by entering the area(s): when no daylight or daylight-independent"
                conditions:
                  - condition: trigger
                    alias: "Triggered by entering the area(s)"
                    id:
                      - presence_on
                  - condition: template
                    alias: "'No daylight' or 'daylight independent'"
                    value_template: >-
                      {{ states('binary_sensor.daylight') == 'off' or daylight_independent }}

                # Lights on when when daylight ends whilepresence is detected 
                # in the area(s).
                
              - condition: and
                alias: "Triggered by daylight ending: when someone's present in the area(s)"
                conditions:
                  - condition: trigger
                    alias: "Triggered by daylight ending"
                    id:
                      - daylight_off
                  - condition: state
                    alias: "Someone's present in the area(s)"
                    entity_id: !input presence_sensor
                    state:
                      - "on"

        sequence:
          - if:
              - condition: template
                alias: Temporary scene with last lights state is defined
                value_template: "{{ states['scene.'+scene_name] != none }}"
            then:

              # Restore a snapshot state of lights recorded
              # when leaving last time. Delete the snapshot afterwards.

              - action: scene.turn_on
                alias: Restore selected lights from the temporary scene
                metadata: {}
                data:
                  entity_id: scene.{{scene_name}}
              - action: scene.delete
                alias: Delete the temporary scene
                metadata: {}
                data:
                  entity_id: scene.{{scene_name}}

            else:

              # If no snapshot to restore, just turn on
              # the default/initial set of lights.

              - action: light.turn_on
                alias: Turn on default/minimal set of lights
                metadata: {}
                data: {}
                target: !input lights_on
      
      # Conditions for lights off

      - alias: "Lights OFF"
        conditions:

          # Lights off when leaving the area

          - condition: trigger
            alias: Triggered by leaving the area(s)
            id:
              - presence_off
          - condition: template
            alias: There are any lights turned on
            value_template: >-
              {{any_lights_on}}

        sequence:

          # Store a snapshot of the current lights in the area
          # as a temporary, dynamic scene.

          - action: scene.create
            alias: Snapshot the selected lights into a temporary scene
            metadata: {}
            data:
              scene_id: "{{scene_name}}"
              snapshot_entities: >-
                {{ lights_restore_entities }}

          # Turn off all the defined lights

          - action: light.turn_off
            alias: Turn off all lights in the area
            metadata: {}
            data: {}
            target: 
              entity_id: >
                {{ lights_off_entities }}

          # When an expiration time for the stored snapshot
          # is set, wait for the snapshot to expire and remove it.
          # Any subsequent calls will break the timeout
          # due to mode:restart.

          - if:
              - condition: template
                alias: Restoration expiration delay has been set
                value_template: "{{ restore_scene_ttl != 0 }}"
            then:
              - delay: !input restore_scene_ttl
                alias: Wait out the expiration time
              - action: scene.delete
                alias: Delete the temporary scene
                metadata: {}
                data:
                  entity_id: scene.{{scene_name}}

mode: restart
