# Tuya Beken CBU (BK7231N)
# https://docs.libretiny.eu/boards/cb2s/
# OXT M222 2CH WiFi/Matter Relay
# https://hurt.id3.pl/product-pol-1174-Modul-OXT-przekaznik-2-obwody-Matter-Wi-Fi-Homekit.html

bk72xx:
  board: cb2s

# Configuration
substitutions:

  name: "bk72-oxt-lazienka-int"
  friendly_name: "OXT M222"

  # Debug
  hide_diagnostic_components: "true"

packages:
  - !include packages/template_bk.yaml
  - !include packages/oxt_m222.yaml

# ============================================================================

# Using UDP to allow managing the local L2 relay from [bk72-oxt-lazienka-ext]. 
# For each of these two relays, only the L2 is wired to a physical device, 
# while L1 is disconnected and it's switch serves just a logical device 
# to manage the remote partner's L2 output.

udp:
  - id: udp_component
    addresses:
      - 192.168.1.114 # bk72-oxt-lazienka-ext

packet_transport:
  
  - platform: udp
    udp_id: udp_component
    id: udp_transport
    encryption: !secret api_key
    rolling_code_enable: true
    binary_sensors:
      - input_S1
    providers:
      - name: bk72-oxt-lazienka-ext
        encryption: !secret api_key

# These sensors import the information on the corresponding sensors
# from the remote device, and act upon incoming change.

binary_sensor:

  - platform: packet_transport
    id: lazienka_ext_S1_state
    transport_id: udp_transport
    provider: bk72-oxt-lazienka-ext
    remote_id: input_S1
    on_state:
      switch.toggle: switch_L2