# Tuya Beken CBU (BK7231N)
# https://docs.libretiny.eu/boards/cbu/
# Product: ORNO OR-SH-17101 2-channel relay Tuya Smart Wi-Fi+BLE
# https://www.orno.pl/en/przekazniki-dopuszkowe/1624-2-channel-relay-tuya-smart-wi-fi-ble-5908254845062.html

bk72xx:
  board: cbu

# Configuration
substitutions:

  name: "bk72-orno-kuchnia-ledy"
  friendly_name: "ORNO OR-SH-17101"

  # Debug
  hide_diagnostic_components: "true"

packages:
  - !include packages/template_bk.yaml
  - !include packages/orno_sh17101.yaml

# ============================================================================

# Using UDP to manage a remote lamp on [esp-maan-hub-v2] via the S2 switch

udp:
  - id: udp_component
    addresses:
      - 192.168.1.108 # esp-maan-hub-v2

packet_transport:
  
  - platform: udp
    udp_id: udp_component
    id: udp_transport
    encryption: !secret api_key
    rolling_code_enable: true
    binary_sensors:
      - input_S2
    providers:
      - name: esp-maan-hub-v2
        encryption: !secret api_key