# Tuya Beken CBU (BK7231N)
# https://docs.libretiny.eu/boards/cb2s/
# OXT M222 2CH WiFi/Matter Relay
# https://hurt.id3.pl/product-pol-1174-Modul-OXT-przekaznik-2-obwody-Matter-Wi-Fi-Homekit.html

bk72xx:
  board: cb2s

# Configuration
substitutions:

  name: "bk72-oxt-sypialnia-sufit"
  friendly_name: "OXT M222"

  # Debug
  hide_diagnostic_components: "true"

packages:
  - !include packages/template_bk.yaml
  - !include packages/oxt_m222.yaml

# ============================================================================

# Using UDP to manage a remote relay on [bk72-oxt-sypialnia-lampki] via the L2 switch

udp:
  - id: udp_component
    addresses:
      - 192.168.1.124 # bk72-oxt-sypialnia-lampki

packet_transport:

  - platform: udp
    udp_id: udp_component
    id: udp_transport
    encryption: !secret api_key
    rolling_code_enable: true
    binary_sensors:
      - input_S2